name: CI

on:
  push:
    branches:
      - dev

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Установить uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      - name: Установить зависимости
        run: uv sync
      - name: Проверка линтера (Ruff)
        run: uv run ruff check .
      - name: Запуск тестов
        run: uv run pytest -v
        env:
          GREETING: "ci"
          DATABASE_URL: "postgresql://ci:ci@localhost:5432/ci"
